### ISSUE TITLE
ValueError at / The view accounts.decorators.wrapper_function didn't return an HttpResponse object. It returned None instead.

### ISSUE THREAD

**Issue by stromal** [dennisivy/crash-course-CRM#4]
ValueError at /
The view accounts.decorators.wrapper_function didn't return an HttpResponse object. It returned None instead.

https://stackoverflow.com/questions/61026338/sqlite-to-postgresql-not-migrates-django-3-0

**Comment by bharathjinka09** [comment]
Hi, I am also facing the same issue. R u able to solve this?

**Comment by stromal** [comment]
bharathjinka09  this was the answer for me https://stackoverflow.com/a/61129748/10270590

**Comment by Akashno** [comment]
inside the decorator you should return something inside of the wrapper function :
like: return HttpResponse('you are not authorised to view this page')
